version: 2.1

executors:
  node:
    working_directory: /tmp/app
    docker:
      - image: circleci/node:12.14.0

commands:
  restore_npm_cache:
    steps:
      - restore_cache:
          keys:
            - dependency-cache-v1-{{ checksum "package-lock.json" }}
            - dependency-cache-v1
  save_npm_cache:
    steps:
      - save_cache:
          key: dependency-cache-v1-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules

jobs:
  build:
    working_directory: /tmp/app
    docker:
      - image: circleci/node:12.14.0
    steps:
      - checkout
      - restore_npm_cache
      - run: npm install
      - save_npm_cache
      - run: npm run generate
      - persist_to_workspace:
          root: /tmp/app
          paths:
            - dist
  deploy:
    parameters:
      env:
        type: enum
        enum: ["staging", "production"]
    working_directory: /tmp/app
    docker:
      - image: okamos/aws-cli:1.16.306
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/app
      - run:
          name: Deploy assets
          command: |
            aws s3 cp --recursive --acl=public-read dist/ s3://okamos-<< parameters.env >>
            aws s3 cp --acl=public-read --metadata-directive "REPLACE" --cache-control "no-cache" dist/index.html s3://okamos-<< parameters.env >>
            echo ${ECHO_TEST_<< parameters.env >>}
workflows:
  flow:
    jobs:
      - build
      - deploy:
          env: staging
          requires:
            - build
          filters:
            branches:
              only: deploy/staging
      - deploy:
          env: production
          requires:
            - build
          filters:
            branches:
              only: deploy/production
